- name: Install HTTP Packages
  yum: name=httpd update_cache=yes state=latest

- name: Install mod-ssl and from rpm
  dnf: name=mod_ssl state=latest
 
- name: Create Apache Document Root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "apache"
    group: "apache"
    mode: '0755'
 
- name: Set up Apache VirtualHost
  template:
    src: "files/httpd.conf"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy server-cert.pem
  copy:
    src: "files/server-cert.pem"
    dest: "/etc/ssl/certs/httpd/server-cert.pem"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy server-key.pem
  copy:
    src: "files/server-key.pem"
    dest: "/etc/ssl/certs/httpd/server-key.pem"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start httpd service
  systemd: name=httpd state=started enabled=yes