- name: Install PHP Remi Repository
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-8.rpm update_cache=yes state=latest
 
- name: Reset PHP Repository
  command: dnf module reset php -y
- name: Enable PHP remi Repository
  command: dnf module enable php:remi-7.4 -y
- name: Install PHP Extensions
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"